---
title: "state-college-east-3-precinct-26"
author: "Rick Gilmore"
date: "April 26, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
precinct.26 = read.csv("state-college-east-3-precinct-26.csv", header=TRUE)
library(ggplot2)
```


## Votes cast

```{r}
p1 = qplot( x=year, y=cast, 
            data=precinct.26, 
            color=type, 
            geom=c("point", "line")
            ) + labs(title="Votes Cast By Year and Election Type -- Precinct 26: State College East 3")
ggsave(filename="votes-cast.png", plot=p1)
p1
```

## Turnout

```{r}
p2 = qplot( x=year, y=cast/registered, 
              data=precinct.26, 
              color=type, 
              geom=c("point", "line")
) + labs(title="Turnout Proportion By Year and Election Type -- Precinct 26: State College East 3")
ggsave(filename="turnout-p.png", plot=p2)
p2
```

## Registered

```{r}
p3 = qplot( x=year, y=registered, 
            data=precinct.26, 
            color=type, 
            geom=c("point", "line")
) + labs(title="Registered Voters By Year and Election Type -- Precinct 26: State College East 3")
ggsave(filename="registered.png", plot=p3)
p3
```
